name: 云端提取 BOOT 分区

on:
  workflow_dispatch:
    inputs:
      rom_url:
        description: 'ROM 下载直链'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/tissot/20231010/lineage-19.1-20231010-nightly-tissot-signed.zip'


jobs:
  YIJIANTIQU:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装依赖
        run: |
          start_time=$(date +%s)
          sudo apt-get update
          sudo apt install aria2
          BUILD_TIME=$(TZ=Asia/Shanghai date +"%m%d%H%M")
          echo "BUILD_TIME=$BUILD_TIME" >> $GITHUB_ENV
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type": "post", "content": {"post": {"zh_cn": {"title": "提取进度更新通知", "content": [[{"tag": "text", "text": "新提取任务已被创建: "}, {"tag": "text", "text": "新提取任务唯一GITHUB WORKFLOWS编号为:${{ github.run_id }}             "}, {"tag": "text", "text": "ROM 下载直链：${{ github.event.inputs.rom_url }}"}]]}}}}' ${{ secrets.FEISHU }}
          

      - name: 提取镜像
        run: |
          cd ~
          mkdir 1
          cd ~
          wget https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
          tar -zxvf payload-dumper-go_1.2.2_linux_amd64.tar.gz
          aria2c -s 10 -x 10 -d . -o firmware.zip "${{ github.event.inputs.rom_url }}"
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type": "post", "content": {"post": {"zh_cn": {"title": "提取进度更新通知", "content": [[{"tag": "text", "text": "任务GITHUB WORKFLOWS编号为:${{ github.run_id }}         "}, {"tag": "text", "text": "ROM 本体已下载完成!开始提取镜像!"}]]}}}}' ${{ secrets.FEISHU }}
          chmod +x payload-dumper-go
          ./payload-dumper-go -p boot,init_boot -o ~/1 firmware.zip
          cd ~
          git clone https://github.com/ColdWindScholar/Magisk_Patch_Python.git
          cd Magisk_Patch_Python
          chmod -R /bin/Linux/x86_64/magiskboot
          python patch.py ~/1/boot.img
          mv Magisk_Patch_Python/new-boot.img ~/1/
          mv ~/1/new-boot.img magisk-boot.img
          cd ${{ github.workspace }}
          end_time=$(date +%s)
          execution_time=$((end_time - start_time))
          touch info.md
          echo "提交日期：$(TZ=Asia/Shanghai date '+%Y-%m-%d %H:%M:%S')" >> info.md
          echo "ROM 下载直链：${{ github.event.inputs.rom_url }}" >> info.md
          echo "本次提取时长为 $execution_time 秒" >> info.md
          curl -X POST -H "Content-Type: application/json" -d '{"msg_type": "post", "content": {"post": {"zh_cn": {"title": "提取进度更新通知", "content": [[{"tag": "text", "text": "新提取任务已完成: "}, {"tag": "text", "text": "任务GITHUB WORKFLOWS编号为:${{ github.run_id }}               "}, {"tag": "text", "text": "ROM 下载直链：${{ github.event.inputs.rom_url }}                             |                 "},{"tag": "a", "text": "点我跳转下载链接", "href": "https://github.com/tosasitill/FeishuBOOT/releases/"}]]}}}}' ${{ secrets.FEISHU }}

      - name: 上传镜像及相关信息
        uses: ncipollo/release-action@v1.12.0
        with:
            artifacts: "~/1/*"
            bodyfile: "${{ github.workspace }}/info.md"
            tag: "OUTPUT_${{ env.BUILD_TIME }}_${{ github.run_id }}"
            token: ${{ secrets.GITHUB_TOKEN }}